// Regenerates README.md / README.en.md from the live directory API.
//
// The repo is a mirror of the directory, not a second source of truth: every
// number here comes from /api/public, so the table cannot drift from the site.
// Affiliate URLs are deliberately never fetched or written -- the repo links to
// the directory, and the directory owns attribution via its own /go/<slug>.
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SITE = (process.env.SITE_ORIGIN || "https://zongjie-nav-pages.pages.dev").replace(/\/+$/, "");
const API = `${SITE}/api/public`;
const HOST = SITE.replace(/^https?:\/\//, "");

// ✅ supported, — unsupported, • not yet verified.
const SUPPORT = { yes: "✅", no: "—", unknown: "•" };

const COPY = {
  zh: {
    file: "README.md",
    langSwitch: "**中文** · [English](README.en.md)",
    title: "宗介中转导航 · 中转站倍率对照表",
    intro: (c) =>
      `收录 **${c.published}** 个 AI API 中转站的参考倍率、模型支持与签到情况，`
      + `其中 ${c.public_benefit} 个公益站、${c.checkin} 个支持签到。`
      + `数据每日自动同步自[导航站](${SITE})。`,
    siteCta: `👉 **完整目录与注册入口：[${HOST}](${SITE})**`,
    hTable: "倍率对照表",
    hFree: "公益站",
    hCheckin: "支持签到",
    hNotes: "字段说明",
    hDisclosure: "推广关系披露",
    tableIntro: "按参考倍率从低到高排列。倍率越低越便宜。",
    th: {
      name: "站点", domain: "域名", rate: "参考倍率",
      codex: "Codex", claude: "Claude Code", fast: "Fast",
      checkin: "签到", models: "模型", tags: "标签",
    },
    yes: "支持",
    no: "不支持",
    notes: [
      "**参考倍率**：站点公示的价格倍率，越低越便宜。倍率随时调整，以各站页面为准。",
      "**Codex / Claude Code / Fast**：✅ 支持，— 不支持，• 待验证。",
      "**签到**：是否提供每日签到额度。",
      "**公益站**：提供免费额度的站点。",
    ],
    disclosure: [
      "本表只提供信息比较，不提供中转服务，也不构成背书。",
      `导航站的注册入口可能包含推广关系：通过入口注册可能给站长带来返利，你支付的价格不因此增加。**本仓库不包含任何推广链接。**`,
      "请勿向第三方中转站提交密码、私钥或其他敏感数据。",
    ],
    freeIntro: "提供免费额度的站点：",
    checkinIntro: "提供每日签到额度的站点：",
    none: "（暂无）",
    footer: (date, n) =>
      `> 本表由 [\`scripts/build-readme.mjs\`](scripts/build-readme.mjs) 自动生成 · 数据快照 ${date} · 共 ${n} 个站点\n`
      + `> 倍率波动较快，注册前请以各中转站页面为准。`,
  },
  en: {
    file: "README.en.md",
    langSwitch: "[中文](README.md) · **English**",
    title: "Zongjie Relay Directory · AI API Relay Rate Comparison",
    intro: (c) =>
      `Reference price multipliers, model support and daily check-in status for **${c.published}** AI API relay providers`
      + ` — ${c.public_benefit} with a free tier, ${c.checkin} offering daily check-in.`
      + ` Synced daily from the [directory](${SITE}/en).`,
    siteCta: `👉 **Full directory and sign-up links: [${HOST}](${SITE}/en)**`,
    hTable: "Rate comparison",
    hFree: "Free tier",
    hCheckin: "Daily check-in",
    hNotes: "Column reference",
    hDisclosure: "Affiliate disclosure",
    tableIntro: "Sorted by reference rate, lowest first. A lower rate is cheaper.",
    th: {
      name: "Provider", domain: "Domain", rate: "Rate",
      codex: "Codex", claude: "Claude Code", fast: "Fast",
      checkin: "Check-in", models: "Models", tags: "Tags",
    },
    yes: "Yes",
    no: "No",
    notes: [
      "**Rate** — the provider's published price multiplier; lower is cheaper. Rates change often, so the provider's own page is authoritative.",
      "**Codex / Claude Code / Fast** — ✅ supported, — unsupported, • unverified.",
      "**Check-in** — whether the provider grants a daily check-in credit.",
      "**Free tier** — providers offering free credits.",
    ],
    disclosure: [
      "This list is an information comparison only. It is not a relay service and not an endorsement.",
      "Sign-up links on the directory may carry a referral relationship: signing up through them may earn the maintainer a rebate, and it does not raise the price you pay. **This repository contains no referral links.**",
      "Never send passwords, private keys or other sensitive data to a third-party relay.",
    ],
    freeIntro: "Providers offering free credits:",
    checkinIntro: "Providers offering a daily check-in credit:",
    none: "(none)",
    footer: (date, n) =>
      `> Generated by [\`scripts/build-readme.mjs\`](scripts/build-readme.mjs) · snapshot ${date} · ${n} providers\n`
      + `> Rates move quickly — always confirm on the provider's own page before signing up.`,
  },
};

// A markdown table cell cannot contain a raw pipe or a line break.
function cell(value) {
  const text = String(value ?? "").replace(/\r?\n+/g, " ").replace(/\|/g, "\\|").trim();
  return text || "—";
}

// A trailing note is optional. Unlike a table cell, an absent note should
// collapse instead of rendering a placeholder dash after the em dash.
function plain(value) {
  return String(value ?? "").replace(/\r?\n+/g, " ").trim();
}

// checkinNote is operator-written Chinese ("支持签到", "每日签到送额度"). Echoing it
// verbatim into an English sentence leaves untranslated copy mid-line, so the
// English page falls back to its own label unless the note carries
// language-neutral detail (an amount, a cadence) worth preserving.
const CJK = /[　-〿㐀-䶿一-鿿＀-￯]/;

function checkinNote(locale, station) {
  const note = plain(station.checkinNote);
  if (!note || (locale === "en" && CJK.test(note))) return COPY[locale].checkinFallback;
  return note;
}

// Multipliers are free text ("0.06x", "1x起", ""), so sort on the leading
// number and push anything unparseable to the end instead of guessing.
function rateValue(multiplier) {
  const match = String(multiplier ?? "").match(/\d+(?:\.\d+)?/);
  return match ? Number.parseFloat(match[0]) : Number.POSITIVE_INFINITY;
}

function shanghaiDate() {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(new Date());
}

// shields.io reads a single dash as the field separator, so a literal dash in
// the label or message has to be doubled or the badge renders mangled.
function badgeField(value) {
  return encodeURIComponent(String(value).replace(/-/g, "--"));
}

// checkinNote is free-form Chinese entered in the admin UI. Most notes just
// restate the boolean ("支持签到"), which reads as untranslated filler on the
// English page, so fall back to the locale's own word there. A note carrying
// concrete detail (a quota, an amount) is kept even in English: an unlocalised
// number is more useful to the reader than silently dropping the information.
function checkinLabel(copy, station) {
  const note = String(station.checkinNote ?? "").trim();
  if (!note) return copy.yes;
  if (copy.file === "README.md") return cell(note);
  return /[0-9A-Za-z$￥¥]/.test(note) ? cell(note) : copy.yes;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchDirectoryOnce() {
  const response = await fetch(API, {
    headers: { accept: "application/json" },
    signal: AbortSignal.timeout(20000),
  });
  if (!response.ok) throw new Error(`${API} returned HTTP ${response.status}`);
  const data = await response.json();
  if (!Array.isArray(data.stations)) throw new Error(`${API} returned no station array`);
  // An empty catalog almost certainly means an upstream fault. Committing an
  // empty table over a good one is worse than failing the run.
  if (data.stations.length === 0) throw new Error(`${API} returned zero stations; refusing to overwrite`);
  if (!data.counts) throw new Error(`${API} returned no counts object`);
  return data;
}

// A single TLS reset or edge hiccup should not fail the daily run and leave the
// table looking stale, so retry with backoff before giving up. Every attempt is
// logged so a genuinely broken API is still obvious in the Action output.
async function loadDirectory(attempts = 4) {
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await fetchDirectoryOnce();
    } catch (error) {
      lastError = error;
      const reason = error?.cause?.code || error?.message || String(error);
      console.error(`attempt ${attempt}/${attempts} failed: ${reason}`);
      if (attempt < attempts) await sleep(attempt * 3000);
    }
  }
  throw lastError;
}

function renderTable(copy, stations) {
  const head = [
    copy.th.name, copy.th.domain, copy.th.rate,
    copy.th.codex, copy.th.claude, copy.th.fast,
    copy.th.checkin, copy.th.models, copy.th.tags,
  ];
  const align = [":--", ":--", "--:", ":-:", ":-:", ":-:", ":-:", ":--", ":--"];
  const rows = stations.map((station) => [
    // The repo links to the directory, never straight to an affiliate URL.
    `**${cell(station.name)}**${station.publicBenefit ? " ★" : ""}`,
    `\`${cell(station.displayDomain)}\``,
    cell(station.multiplier),
    SUPPORT[station.codexSupport] || SUPPORT.unknown,
    SUPPORT[station.claudeCodeSupport] || SUPPORT.unknown,
    SUPPORT[station.fastSupport] || SUPPORT.unknown,
    station.supportsCheckin ? SUPPORT.yes : SUPPORT.no,
    cell((station.models || []).join(", ")),
    cell((station.tags || []).slice(0, 4).join(", ")),
  ]);
  return [
    `| ${head.join(" | ")} |`,
    `| ${align.join(" | ")} |`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ].join("\n");
}

function renderList(copy, stations, note) {
  if (stations.length === 0) return copy.none;
  return stations
    .map((station) => `- **${cell(station.name)}** \`${cell(station.displayDomain)}\`${note(station) ? ` — ${note(station)}` : ""}`)
    .join("\n");
}

function renderReadme(locale, { counts, stations, settings }) {
  const copy = COPY[locale];
  const ordered = [...stations].sort((a, b) =>
    rateValue(a.multiplier) - rateValue(b.multiplier)
    || String(a.name).localeCompare(String(b.name), locale === "zh" ? "zh-CN" : "en"));
  const free = ordered.filter((station) => station.publicBenefit);
  const checkin = ordered.filter((station) => station.supportsCheckin);
  const date = shanghaiDate();

  return [
    `# ${copy.title}`,
    "",
    copy.langSwitch,
    "",
    `[![stations](https://img.shields.io/badge/stations-${badgeField(counts.published)}-2563eb)](${SITE})`
    + ` [![free tier](https://img.shields.io/badge/free%20tier-${badgeField(counts.public_benefit)}-16a34a)](${SITE})`
    + ` [![updated](https://img.shields.io/badge/updated-${badgeField(date)}-6366f1)](${SITE})`,
    "",
    copy.intro(counts),
    "",
    copy.siteCta,
    "",
    `## ${copy.hTable}`,
    "",
    copy.tableIntro,
    "",
    renderTable(copy, ordered),
    "",
    `## ${copy.hFree}`,
    "",
    copy.freeIntro,
    "",
    renderList(copy, free, (station) => cell(station.multiplier)),
    "",
    `## ${copy.hCheckin}`,
    "",
    copy.checkinIntro,
    "",
    renderList(copy, checkin, (station) => checkinLabel(copy, station)),
    "",
    `## ${copy.hNotes}`,
    "",
    copy.notes.map((line) => `- ${line}`).join("\n"),
    "",
    `## ${copy.hDisclosure}`,
    "",
    copy.disclosure.map((line) => `- ${line}`).join("\n"),
    "",
    "---",
    "",
    copy.footer(date, ordered.length),
    "",
  ].join("\n");
}

// The snapshot is the machine-readable half of this mirror: build-broadcast.mjs
// diffs two committed revisions of it to find real rate movement. It is written
// from the same fetch as the tables, so the tables, the snapshot and the site
// can never disagree.
//
// It deliberately carries NO generated-at timestamp and only the fields the
// broadcast reports on. Any volatile field would make the file differ on every
// run and destroy its only job: answering "did anything actually change?".
function renderSnapshot({ counts, stations }) {
  const rows = [...stations]
    .sort((a, b) => String(a.slug).localeCompare(String(b.slug)))
    .map((station) => ({
      slug: String(station.slug ?? ""),
      name: String(station.name ?? ""),
      multiplier: String(station.multiplier ?? ""),
      publicBenefit: station.publicBenefit === true,
      supportsCheckin: station.supportsCheckin === true,
    }));
  const snapshot = {
    counts: {
      published: counts.published,
      public_benefit: counts.public_benefit,
      checkin: counts.checkin,
    },
    stations: rows,
  };
  return `${JSON.stringify(snapshot, null, 2)}\n`;
}

const directory = await loadDirectory();
const written = [];
for (const locale of ["zh", "en"]) {
  const target = path.join(rootDir, COPY[locale].file);
  const body = renderReadme(locale, directory);
  writeFileSync(target, body, "utf8");
  written.push({ locale, file: COPY[locale].file, bytes: Buffer.byteLength(body, "utf8") });
}

const snapshotDir = path.join(rootDir, "data");
mkdirSync(snapshotDir, { recursive: true });
const snapshotPath = path.join(snapshotDir, "stations.json");
const snapshotBody = renderSnapshot(directory);
writeFileSync(snapshotPath, snapshotBody, "utf8");
written.push({ locale: "-", file: "data/stations.json", bytes: Buffer.byteLength(snapshotBody, "utf8") });

console.log(JSON.stringify({
  api: API,
  stations: directory.stations.length,
  counts: directory.counts,
  written,
}, null, 2));
